name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual runs from the Actions UI for debugging
  workflow_dispatch: {}
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install server deps
        working-directory: server
        run: |
          if [ -f package-lock.json ]; then npm ci --no-audit --no-fund; else npm install --no-audit --no-fund; fi

      - name: Lint (server)
        working-directory: server
        run: |
          if npm run -s lint --silent; then echo 'lint ok'; else echo 'no lint or lint failed'; fi

      - name: Test (server)
        working-directory: server
        run: |
          if npm test --silent; then echo 'tests ok'; else echo 'no tests or tests skipped'; fi

      - name: Start server and smoke test
        working-directory: server
        run: |
          nohup npm run start --silent &> server.out & echo $! > server.pid || true
          sleep 4
          curl -fS http://localhost:8002/api/v1/healthcheck || (tail -n +1 server.out && false)

  client:
    runs-on: ubuntu-latest
    needs: server
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install client deps
        working-directory: client
        run: |
          if [ -f package-lock.json ]; then npm ci --no-audit --no-fund; else npm install --no-audit --no-fund; fi

      - name: Build client
        working-directory: client
        run: |
          npm run build --silent

      - name: Upload client build
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: client/dist
